yaml
name: Deploy to Lightsail
   on:
     push:
       branches:
         - main  # Change this to your main branch name

   jobs:
     deploy:
       runs-on: ubuntu-latest  # You can choose the appropriate runner for your use case

       steps:
         - name: Checkout Code
           uses: actions/checkout@v2  # This step checks out your code

         - name: Deploy to Lightsail
           run: |
             # Add your deployment script or commands here
             # For example, you might use SSH to copy files to your Lightsail server and restart the web server.
             # Replace <your-server-ip> with your server's IP address or hostname.
             sudo -i
             ssh -i /home/ubuntu/DreamGurukul/ ubuntu@3.219.62.113 'cd /var/www/DreamGurukul && git pull origin main'

           env:
             SERVER_SSH_KEY: ${{ secrets.PuTTY-User-Key-File-3: ssh-rsa
Encryption: none
Comment: DreamGatewayAWSProd
Public-Lines: 6
AAAAB3NzaC1yc2EAAAADAQABAAABAQCD0cfJ3vgqFQOjDs31KLQKCK8vdkrqK4BS
BzpIl97H5SomQ8LT2WRozepjh/ARCLRZzDbP38ItsGG3dD5JctBr9yG6mP0WoYcF
mF1YwjRZGY3gIl6eLQOPASbw1KtDKUPHLG8bxL6voxJX35yiHbGd2HlN3u6JcTqs
+I2hYiiDEH8BY5yT6aNBORW7y6zEDRZwskz1N7R8YjWiD74jP1W7nkSsyPCsv/MV
Q7sAu3/1kdR69hQde1rUwJkDuGCWF8WvnD0cscfUW+enmXCFXb3WQV5JoO+mo5y5
O4yosjEYNtotkLFBBT2kpe1MHh++7iKpMR3dZ/zyYZOpQ+nX8Jc/
Private-Lines: 14
AAABAGTqrJaKwdiNv/wMcHbY04S/A0dFu7Ks3Q9vgxpiUmcctXkX9Ub0rl9iDahn
QM35qQD6S5g3SNRrrVOihbD7Wj7dsw/E4jV6MgGBlS1HeIYh/zDxfxh/g7Lugd5s
IjVHmSEZjnJm3ElggcGOar7eFsWuHagVHO9SJUaY/uznVfaICCx2ZXT5trDkq4mm
R+oa8kLPWJqhi/1F4NDCpL+04KMjxNHMj42ldheIoXnLU7ohU4+tlxo+pqDnQ9pk
lU4w4O66rjC2PkgWKA+JCx9k5PuGGz/ED1BJlVS+5p684Fu6XbXFQjQkE7Aa1CRI
cCQ+SKcwsHGPJylaiPzYwTi3XWkAAACBALu47OMTBV7YtN9Z1EOtf3WButeuazzj
V2ytFoKAQGulIBAJubqnh7LW/UD6AqRyt9S2sLmk1HloIdReSrJIeVscWQu6X3C8
a1bD5HbkpPdd3FoQDVoD1GtNn3icFajJDfm+Pgt0PnwgEWlv41XZvK01AL0FI64i
57QwmgG9LSalAAAAgQCzw6l/nEEyrK1GHy17dvux0DJGnZ/ig2dci0vp85Lr53pX
5Xg4eTtQTjN9pENc80GG+pRaqTJlCAh4Nv200e6RhLJ+8qt+WBwT+bUtBDO+t7rE
hyK8S2/zErcmRYaNElyND9PW1Nd+FEpI7sYSANXl0gZD8Z9YZ8cMnW1rAgeFEwAA
AIAeOhiTMWWeknzbfWmm/KD5VjicJCr5PJWZAsoysdsLHMZlW+LU3vnGdWw2HzHL
q3+02ffDOo0ZiS+JmMDDG8oxcqGPq99Eo6sXZGMPXkUbfGcyKVKYuHNwiIrQ6rUG
ndPSsOoALBLVBB5N76GO2Kns5bhQsWxiJSSby0a07F57zA==
Private-MAC: 95934e6ddbdd5edac8301072662cc6f0d271bc2a4fb241883d2a758e78141b08
 }}  # Store your SSH key as a GitHub secret